title: Aditya Pandey
description: First-year CSE student at MIT Manipal. Builder. Thinker. K0RAG.
baseurl: ""
url: "https://k0rag.github.io"
author: Aditya Pandey
email: pandeyaditya1053@gmail.com

github_username: K0RAG
instagram_username: aditya_1053_
linkedin_username: Aditya Pandey

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Aditya Pandey"
